version: "3.9"

services:
  app:
    build:
      context: .
    ports:
      - "5500:5500"
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=production
    command: gunicorn -w 4 -b 0.0.0.0:5500 app:app
